### PR TITLE
Adds b3:0 header to avoid trace amplification when using proxies

### PR DESCRIPTION
**Pull request by adriancole**
Same as https://github.com/openzipkin/zipkin-go/pull/176

### CODE REVIEW

**Review by shakuzen — COMMENTED** [review]
LGTM

**Review by anuraaga — COMMENTED** [review]
Just wondering, shouldn't we set `x-b3` too? Aren't there proxies that don't support `b3` and would have write amplification? Or does `proxy` == `envoy` now adays (I'd buy it :P)

**Comment by adriancole** [comment]
good question: more bytes on the wire, and would prefer to let such an old proxy that doesn't know "b3" yet, and needs this, become known! I'd prefer to convince them to support "b3" rather than force another and longer header on everyone.

**Comment by adriancole** [comment]
https://github.com/openzipkin/b3-propagation/pull/42

**Pull request merged**
