### PR TITLE
Routine dependency updates

### PR DESCRIPTION
**Pull request by reta**
Routine dependency updates

### CODE REVIEW

**Review by shakuzen — APPROVED** [review]

**Review by codefromthecrypt — APPROVED** [review]
thanks again! wanna do the honors of pushing the release tag?

**Comment by shakuzen** [comment]
It looks like deploying the bom was successful but the jars failed: https://github.com/openzipkin/zipkin-reporter-java/actions/runs/10792310306
Can we re-run the job or do we need to manually do something to finish the release?

**Comment by codefromthecrypt** [comment]
smells like a sonatype timeout. maybe double-check they didn't make it to central. If not, double check with the sonatype oss login. regardless, running again shouldn't hurt as maven prevents double-uploading server-side

p.s. I noticed they changed since I last looked to require an email instead of a username login https://ossindex.sonatype.org/user/signin

**Comment by shakuzen** [comment]
It looks like none of the jars made it to central ([dependabot PR to upgrade](https://app.circleci.com/pipelines/github/micrometer-metrics/tracing/1716/workflows/ca88015a-1d14-40a9-ac12-2fa81884eb27/jobs/8153) is failing to find any of the jars). I've re-run the deploy jars job now and [it was successful](https://github.com/openzipkin/zipkin-reporter-java/actions/runs/10792310306/job/29968516175). Things should be in central soon.

**Pull request merged**
